services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '8883:8883'
      - '1883:1883'
    restart: unless-stopped
